# Generated by Django 2.1.3 on 2018-11-12 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20181112_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='user_rel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
